wuhanproject/account/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    registration_view,
    login_view,
    logout_view,
    account_view,
    must_authenticate_view,
)

app_name = 'account'

urlpatterns = [
    path('', account_view, name='account'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('register/', registration_view, name='register'),
]

wuhanproject/forum/urls.py
from django.urls import path
from .views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    delete_blog_view,
    delete_comment_view,
    post_list_view,
    up_vote_view,
)

app_name = 'forum'

urlpatterns = [
    path('', post_list_view, name="post_list"),
    path('create/', create_blog_view, name="create"),
    path('<id>/<title>/', detail_blog_view, name="detail"),
    path('<id>/<title>/edit/', edit_blog_view, name="edit"),
    path('<id>/<title>/delete/', delete_blog_view, name='delete'),

    # comments
    path('<id>/<title>/comment/<cid>/delete', delete_comment_view, name='comment_delete'),

    # vote
    path('up/<id>/<title>', up_vote_view, name='up_vote'),

]

wuhanproject/wuhanproject/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    re_path(r'^', include('baseapp.urls', 'baseapp')),
    path('forum/', include('forum.urls', 'forum')),
    path('account/', include('account.urls', 'account')),

    #path('tinymce/', include('tinymce.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    # https://www.뭐뭐닷컴.com/payment/paypal 이걸 paypal의 ipn 설정에 입력하면 된다.
]

urlpatterns += staticfiles_urlpatterns()
from django.views.generic import TemplateView

# 이 아래부분 미디어 파일 디벨롭모드에서 쓰기 위해 필요
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        # path('admin/', admin.site.urls),
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
        re_path(r'^a/admin/', admin.site.urls),
    ]

wuhanproject/templates/snippets/base_css.html
<style type="text/css">
	body{
		background-color: #ffffff;
	}
</style>

wuhanproject/templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<!-- Footer -->
<div class="py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <p class="mb-0">Made by OXIBUG&nbsp;<br>Contact us: coronagram1212@gmail.com</p>
            </div>
        </div>
    </div>
</div>
<!-- End Footer -->

wuhanproject/templates/snippets/header.html
<style type="text/css">
    @media (min-width: 768px) {
        html {
            font-size: 16px;
        }
    }
</style>
<div id="id_q" class="d-none"></div>
<!-- Header -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
        {% if request.user.is_authenticated %}
            <p class="m-auto d-none d-md-block">Hello, {{ request.user.username }}</p>
        {% else %}
            <a href="/"><p class="m-auto d-none d-md-block h4">coronagram</p></a>



        {% endif %}
    </h5>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if request.user.is_authenticated %}
            <a class="p-2 text-dark" href="/">Home</a>
            <a class="p-2 text-dark" href="{% url 'forum:post_list' %}">Forum</a>
            <a class="p-2 text-dark" href="{% url 'account:account' %}">Account</a>
            <a class="p-2 text-dark" href="{% url 'account:logout' %}">Logout</a>
        {% else %}
            <a class="p-2 text-dark" href="/">Home</a>
            <a class="p-2 text-dark" href="{% url 'forum:post_list' %}">Forum</a>
            <a class="p-2 text-dark" href="{% url 'account:login' %}">Login</a>
            <a class="btn btn-outline-primary" href="{% url 'account:register' %}">Register</a>
        {% endif %}

    </nav>
</div>

<!-- End Header -->

<script type="text/javascript">
    document.getElementById("id_q").value = "{{query}}"
</script>