wuhanproject/account/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    registration_view,
    login_view,
    logout_view,
    account_view,
    must_authenticate_view,
)

app_name = 'account'

urlpatterns = [
    path('', account_view, name='account'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('register/', registration_view, name='register'),
]

wuhanproject/forum/urls.py
from django.urls import path
from .views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    delete_blog_view,
    delete_comment_view,
    post_list_view,
    up_vote_view,
)

app_name = 'forum'

urlpatterns = [
    path('', post_list_view, name="post_list"),
    path('create/', create_blog_view, name="create"),
    path('<id>/<title>/', detail_blog_view, name="detail"),
    path('<id>/<title>/edit/', edit_blog_view, name="edit"),
    path('<id>/<title>/delete/', delete_blog_view, name='delete'),

    # comments
    path('<id>/<title>/comment/<cid>/delete', delete_comment_view, name='comment_delete'),

    # vote
    path('up/<id>/<title>', up_vote_view, name='up_vote'),

]

wuhanproject/wuhanproject/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    re_path(r'^', include('baseapp.urls', 'baseapp')),
    path('forum/', include('forum.urls', 'forum')),
    path('account/', include('account.urls', 'account')),

    #path('tinymce/', include('tinymce.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    # https://www.뭐뭐닷컴.com/payment/paypal 이걸 paypal의 ipn 설정에 입력하면 된다.
]

urlpatterns += staticfiles_urlpatterns()
from django.views.generic import TemplateView

# 이 아래부분 미디어 파일 디벨롭모드에서 쓰기 위해 필요
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        # path('admin/', admin.site.urls),
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
        re_path(r'^a/admin/', admin.site.urls),
    ]

wuhanproject/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyAccountManager()

    def __str__(self):
        return self.username

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

wuhanproject/forum/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django import template

register = template.Library()


class Post(models.Model):
    title = models.CharField(max_length=80, null=False, blank=False)
    body = models.TextField(max_length=5000, blank=True, null=True)
    featured = models.BooleanField(default=False)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")  # 글을 수정하지 않으면 date_published와 동일
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    accumulated_comment_count = models.IntegerField(default=0, blank=None, null=True)

    # featured                = models.BooleanField()                         # JustDjango
    # categories              = models.ManyToManyField(Category)              # 글의 카테고리를 객관식으로 지정 가능. admin이 설정을 해주어야 한다.

    def __str__(self):
        return self.title

    def get_absolute_url(self):  # JustDjango
        return reverse('forum:detail', kwargs={
            'id': self.id,
            'title': self.title
        })

    @property
    def get_comments(self):
        return self.comments.all().order_by('date_updated')

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count() + PostViewIP.objects.filter(post=self).count()

    @property
    def up_count(self):
        return PostUp.objects.filter(post=self).count()


class Comment(models.Model):
    content = models.TextField(max_length=5000, null=False, blank=False)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', related_name='comments', on_delete=models.CASCADE)
    comment_id = models.IntegerField(default=0, blank=None, null=True)

    def save(self, *args, **kwargs):
        new_accumulated_comment_count = self.post.accumulated_comment_count + 1
        self.post.accumulated_comment_count = new_accumulated_comment_count
        self.post.save()
        self.comment_id = new_accumulated_comment_count
        super(Comment, self).save(*args, **kwargs)

    def __str__(self):
        return self.author.username


class PostView(models.Model):  # JustDjango 조회수 체크
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # JustDjango
    post = models.ForeignKey('Post', related_name='post_views', on_delete=models.CASCADE)  # JustDjango

    def __str__(self):
        return self.user.username


class PostViewIP(models.Model):
    ip = models.CharField(max_length=100, null=False, blank=False)  # JustDjango
    post = models.ForeignKey('Post', related_name='post_view_ips', on_delete=models.CASCADE)  # JustDjango

    def __str__(self):
        return self.ip


class PostUp(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # JustDjango
    post = models.ForeignKey('Post', related_name='post_ups', on_delete=models.CASCADE)  # JustDjango

    def __str__(self):
        return self.user

wuhanproject/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2', )


class AccountAuthenticationForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('email', 'username', )

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError('Email "%s" is already in use.' % account)

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError('Username "%s" is already in use.' % username)

wuhanproject/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout

from .forms import RegistrationForm, AccountAuthenticationForm, AccountUpdateForm
from forum.models import Post


def registration_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            # email = form.cleaned_data.get('email')
            # raw_password = form.cleaned_data.get('password1')
            account = form.save()
            # account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('forum:post_list')
        else:
            context['registration_form'] = form

    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'register.html', context)


def logout_view(request):
    logout(request)
    return redirect('forum:post_list')


def login_view(request):
    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect("forum:post_list")

    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect("forum:post_list")

    else:
        form = AccountAuthenticationForm()

    context['login_form'] = form

    # print(form)
    return render(request, "login.html", context)


def account_view(request):
    if not request.user.is_authenticated:
        return redirect("account:login")

    context = {}
    if request.POST:
        form = AccountUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.initial = {
                "email": request.POST['email'],
                "username": request.POST['username'],
            }
            form.save()
            context['success_message'] = "Updated"
    else:
        form = AccountUpdateForm(

            initial={
                "email": request.user.email,
                "username": request.user.username,
            }
        )

    context['account_form'] = form

    blog_posts = Post.objects.filter(author=request.user)
    context['blog_posts'] = blog_posts

    return render(request, "account.html", context)


def must_authenticate_view(request):
    return render(request, 'must_authenticate.html', {})

wuhanproject/templates/account.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }

  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="username"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }
  .h3{
    text-align: center;
  }

  .blog-posts{
    max-width: 500px;
    width: 100%;
    margin: auto;
  }
</style>


<form class="form-signin" method="post">{% csrf_token %}

  <h1 class="h3 mb-3 font-weight-normal">Account</h1>

  <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus value={{account_form.initial.email}}>
  
  <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required
  value="{{account_form.initial.username}}">

  {% for field in account_form %}
      <p>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
  {% endfor %}
  {% if account_form.non_field_errors %}
    <div style="color: red">
      <p>{{account_form.non_field_errors}}</p>
    </div>
      
  {% endif %}

  {% if success_message %}
    <p style="color:green; text-align: center;">{{success_message}}</p>
  {% endif  %}

  <button class="btn btn-lg btn-primary btn-block" type="submit">Save changes</button>

</form>

<div class="d-flex flex-column">
  <a class="m-auto" href="{% url 'password_change' %}">Change password</a>
</div>

<div class="container mt-4 p-4">
  <div class="row">
    <div class="blog-posts">
      <h3 class="mb-3 font-weight-normal">Posts:</h3>
      {% if blog_posts %}
        <ul class="list-group">
        {% for post in blog_posts %}
          <a href="{% url 'forum:detail' id=post.id title=post.title %}" style="text-decoration: none;"><li class="list-group-item">{{post}}</li></a>
        {% endfor %}
        </ul>
      {% else %}
        <p>You have no posts. Create a post <a href="{% url 'forum:create' %}">here</a>.</p>
      {% endif %}
    </div>
  </div>
</div>






{% endblock content %}

wuhanproject/templates/base.html
<!DOCTYPE html>
<html lang=en>

<head>
    <!-- Required meta tags -->
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>coronagram</title>
    {% load static from staticfiles %}
    {% include 'others/header_static.html' %}
    {% include 'others/header_metas.html' %}
    {% include 'others/favicon.html' %}


</head>

<body>
{% include 'snippets/base_css.html' %}
{% include 'snippets/header.html' %}

<!-- Body -->
<style type="text/css">
    a:link {
        color: inherit;
        text-decoration: none;
    }

    a:visited {
        color: inherit;
    }

    a:hover {
        color: inherit;
    }

    a:active {
        color: inherit;
    }

    .main {
        min-height: 100vh;
        height: 100%;
    }
</style>
<div class="main">
    {% block content %}

    {% endblock content %}
</div>
<!-- End Body -->

{% include 'snippets/footer.html' %}

</body>


</html>

wuhanproject/templates/blog_post_snippet.html
<style type="text/css">
    .card {
        width: 100%;
    }

    .card-body {
        padding: 16px;
    }
</style>
{% load tem_extras %}

{% if blog_post %}
    <div class="container">
        {% if query %}
            <div class="row p-1">
                <div class="card m-auto">
                    <div class="card-body mt-2 mb-2">
                        <h2 class="card-title">Search results</h2>
                        <p class="card-text">Results matching the search: "{{ query }}"</p>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="row">
            <!-- Blog Post -->
            <a href="{% url 'forum:detail' id=post.id title=post.title %}">

                <div class="card m-auto">
                    <div class="card-body mt-2 mb-2">
                        <h4 class="card-title">{{ blog_post.title }}</h4>
                        <p class="card-text">{{ blog_post.body|safe|truncatechars:40 }}</p>

                        <header>
                            <h6 class="h6">Comments <span class="no-of-comments">({{ blog_post.comments.count }})</span>
                            </h6>
                        </header>
                        {% if blog_post.author == request.user %}
                            <header class="text-right">
                                <a href="{% url 'forum:edit' id=blog_post.id title=blog_post.title %}"
                                   class="btn btn-primary btn-sm m-1">Edit</a>
                                <a href="{% url 'forum:delete' id=blog_post.id title=blog_post.title %}"
                                   class="btn btn-primary btn-sm m-1">Delete</a>
                            </header>
                        {% else %}
                            <header class="text-right">
                                <a href="{% url 'forum:delete' id=blog_post.id title=blog_post.title %}"
                                   class="btn btn-primary btn-sm m-1 d-none">Delete</a>
                            </header>
                        {% endif %}
                    </div>
                    <div class="card-footer text-muted">
                        {{ blog_post.date_published|timesince }} ago by <span
                            class="font-italic">{{ blog_post.author }}</span> views: {{ blog_post.view_count }}  up: {{ blog_post.up_count }}
                    </div>
                </div>
            </a>

        </div>
    </div>

{% else %}

    <div class="container">
        <div class="row">
            <div class="card m-auto">
                <div class="card-body mt-2 mb-2">
                    <h2 class="card-title">No results</h2>
                    <p class="card-text">There are no results matching the search: "{{ query }}"</p>
                </div>
            </div>
        </div>
    </div>

{% endif %}

wuhanproject/templates/create_blog.html
{% extends 'base.html' %}


{% block content %}

    <style type="text/css">
        .create-form {
            width: 100%;
            max-width: 100%;
            padding: 15px;
            margin: auto;
        }

        .submit-button {
            max-width: 200px;
        }
    </style>

    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-1">
                <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

                    <!-- title -->
                    <div class="form-group">
                        <label for="id_title">Title</label>
                        <input class="form-control" type="text" maxlength="80" name="title" id="id_title" placeholder="Title" required
                               autofocus>
                    </div>

                    <!-- Body -->
                    <div class="form-group">
                        <label for="id_body">Content</label>
                        <textarea class="form-control content" rows="10" type="text" name="body" id="id_body" maxlength=""
                                  placeholder="Please tell us something..." required></textarea>
                    </div>

                    <!-- Submit btn -->
                    <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

wuhanproject/templates/detail_blog.html
{% extends 'base_detail.html' %}


{% block content %}


    <style type="text/css">
        .card {
            max-width: 700px;
        }

        .card-body {
            padding: 20px;
        }

        p {
            margin: 0
        }

        .voted {
            background: #dffcc8;
            solid-color: #3b5998;
            border-color: #1b6d85;
            border-radius: 4px;
            color: #8c8c8c;
        }

        .unvoted {
            background: #7ccbfc;
            border-color: #1b6d85;
            solid-color: #3b5998;
            border-radius: 4px;
            color: #ffffff;
        }
    </style>
    <div class="d-none" id="id">{{ blog_post.id }}</div>
    <div class="d-none" id="title">{{ blog_post.title }}</div>
    <div class="d-none" id="up">{{ blog_post.up_count }}</div>
    <div class="container">
        <div class="row">

            <!-- Blog Post -->
            <div class="col-12 col-md-8 offset-md-2 card mx-auto">
                <div class="card-body mt-2 mb-2">
                    <h4 class="card-title">{{ blog_post.title }}</h4>
                    <p class="card-text">{{ blog_post.body|safe|urlize }}</p>
                    {% if blog_post.author == request.user %}
                        <div class="text-right">
                            <a href="{% url 'forum:edit' id=blog_post.id title=blog_post.title %}"
                               class="btn btn-primary btn-sm">Edit</a>
                            <a href="{% url 'forum:delete' id=blog_post.id title=blog_post.title %}"
                               class="btn btn-primary btn-sm">Delete</a>
                        </div>

                    {% endif %}
                    {% if request.user.is_authenticated %}
                        {% if vote %}
                            <div class="container mt-4">
                                <div class="row">
                                    <div class="col-12 text-center" style=""><a
                                            class="btn text-black 4 p-2 voted vote-btn"
                                            href="">Voted</a> <span class="p-1"
                                                                    id="up_count">{{ blog_post.up_count }}</span></div>
                                </div>
                            </div>

                        {% else %}
                            <div class="container mt-4">
                                <div class="row">
                                    <div class="col-12 text-center" style=""><a
                                            class="btn text-black 4 p-2 unvoted vote-btn"
                                            href="">Up</a> <span class="p-1"
                                                                 id="up_count">{{ blog_post.up_count }}</span></div>
                                </div>
                            </div>

                        {% endif %}

                    {% else %}
                        <div class="container mt-4">
                            <div class="row">
                                <div class="col-12 text-center" style=""><a
                                        class="btn btn-secondary text-black 4"
                                        href="{% url 'account:login' %}">Login to Up</a> <span class="p-1"
                                                                                               id="up_count">{{ blog_post.up_count }}</span>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    <div class="container mt-4">
                        <div class="row">
                            <div class="col-12 text-center" style=""></div>
                        </div>
                    </div>

                    <div class="container mt-4">
                        <div class="row">
                            <div class="col-6 text-center" style=""><a class="btn text-white col-12"
                                                                       href="http://www.facebook.com/sharer.php?u=https://www.coronagram.com{{ request.get_full_path }}"
                                                                       style="background:#3b5998"
                                                                       target="_blank"><i
                                    class="fa fa-facebook-square fa-fw fa-1x py-0"></i> Share</a></div>
                            <div class="col-6 col-md-6 text-center"><a class="btn text-white col-12"
                                                                       href="https://twitter.com/share?url=https://www.coronagram.com{{ request.get_full_path }}"
                                                                       style="background:#55acee"
                                                                       target="_blank"><i
                                    class="fa fa-twitter fa-fw fa-1x py-0"></i>
                                Tweet</a></div>
                        </div>
                    </div>
                </div>

                <div class="post-comments p-2">
                    <header>
                        <h6 class="h6">Comments <span class="no-of-comments">({{ blog_post.comments.count }})</span>
                        </h6>
                    </header>
                    {% for comment in blog_post.get_comments %}
                        <blockquote>
                            <div class="card p-1">
                                <p><span
                                        class="badge badge-secondary">{{ comment.comment_id }}</span> {{ comment.content }}
                                </p>
                                <p>
                                    <small>{{ comment.author.username }} <span
                                            class="font-italic"> {{ comment.date_updated|timesince }} ago</span>
                                    </small>
                                </p>
                                {% if comment.author == request.user %}
                                    <a href="{% url 'forum:comment_delete' id=blog_post.id title=blog_post.title cid=comment.id %}"
                                       class="btn btn-primary btn-sm">Delete</a>
                                {% endif %}
                            </div>
                        </blockquote>

                    {% endfor %}
                </div>
                {% if request.user.is_authenticated %}
                    <div class="add-comment">
                        <form method="POST" action="." class="commenting-form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <small>{{ form }}</small>
                                </div>
                                <div class="form-group col-md-12 text-right">
                                    <button type="submit" class="btn btn-secondary">Submit Comment</button>
                                </div>
                            </div>
                        </form>
                    </div>
                {% else %}
                    <div class="add-comment text-center">
                        <a href="{% url 'account:login' %}">
                            <button class="btn btn-primary">Login to comment</button>
                        </a>
                    </div>
                {% endif %}

                <div class="card-footer text-muted">
                    {{ blog_post.date_updated|timesince }} ago by <span
                        class="font-italic">{{ blog_post.author.username }}</span> views: {{ blog_post.view_count }}
                </div>
            </div>
        </div>
    </div>
    <div class="container pt-4">
        <a href="{% url 'forum:post_list' %}">
            <div class="row">
                <button class="col-md-8 mx-auto text-center btn btn-primary p-2">Post List</button>
            </div>
        </a>
    </div>


{% endblock content %}

wuhanproject/templates/edit_blog.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}


	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" maxlength="80" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control content" rows="10" type="text" name="body" id="id_body" placeholder="Please tell us something..."
					required>{{form.initial.body}}</textarea>
				</div>


				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>


{% endblock content %}

wuhanproject/templates/must_authenticate.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="d-flex flex-column text-center">
		<p class="m-auto">You must authenticate to view this page. </p>

        <a href="{% url 'account:register' %}"><button class="m-auto btn btn-primary">Create an account</button></a>
        <p class="m-auto">or</p>
        <a href="{% url 'account:login' %}"><button class="m-auto btn btn-primary">login</button></a>
	</div>
</div>

{% endblock content %}