wuhanproject/baseapp/urls.py
from django.urls import path, re_path
from baseapp import views
from django.views.generic import TemplateView
from baseapp.sitemaps import sitemaps
from django.contrib.sitemaps import views as sitemap_views
from django.conf.urls.static import static

app_name = 'baseapp'

urlpatterns = [
    re_path(r'^robots\.txt$',
            TemplateView.as_view(template_name="others/robots.txt", content_type="text/plain"), name="robots"),
    path('a/sitemap.xml', sitemap_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'baseapp:sitemaps'}),
    path('a/sitemap-<section>.xml', sitemap_views.sitemap, {'sitemaps': sitemaps},
            name='sitemaps'),
    re_path(r'^$', views.home, name='home'),
    re_path(r'^chart/$', views.chart, name='chart'),
    re_path(r'^news/$', views.news, name='news'),
    re_path(r'^add_post/$', views.add_post, name='add_post'),
    re_path(r'^update_youtube/$', views.update_youtube, name="update_youtube"),
    re_path(r'^update_bbc/$', views.update_bbc, name="update_bbc"),
    re_path(r'^update_country/$', views.update_country, name="update_country"),
]


from django.conf import settings

if settings.DEBUG:

    urlpatterns += [

        #
        # re_path(r'^b/admin/$', views.b_admin, name='b_admin'),
        # re_path(r'^b/admin/solo/$', views.b_admin_solo, name='b_admin_solo'),
        # re_path(r'^b/admin/group/$', views.b_admin_group, name='b_admin_group'),
        # re_path(r'^b/admin/member/$', views.b_admin_member, name='b_admin_member'),
        # re_path(r'^b/admin/group/edit/(?P<uuid>([0-9a-f]{32}))/$', views.b_admin_group_edit, name='b_admin_group_edit'),
        # re_path(r'^b/admin/solo/edit/(?P<uuid>([0-9a-f]{32}))/$', views.b_admin_solo_edit, name='b_admin_solo_edit'),
    ]

wuhanproject/forum/urls.py
from django.urls import path
from .views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    delete_blog_view,
    delete_comment_view,
    post_list_view,
    up_vote_view,
)

app_name = 'forum'

urlpatterns = [
    path('', post_list_view, name="post_list"),
    path('create/', create_blog_view, name="create"),
    path('<id>/<title>/', detail_blog_view, name="detail"),
    path('<id>/<title>/edit/', edit_blog_view, name="edit"),
    path('<id>/<title>/delete/', delete_blog_view, name='delete'),

    # comments
    path('<id>/<title>/comment/<cid>/delete', delete_comment_view, name='comment_delete'),

    # vote
    path('up/<id>/<title>', up_vote_view, name='up_vote'),

]

wuhanproject/wuhanproject/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    re_path(r'^', include('baseapp.urls', 'baseapp')),
    path('forum/', include('forum.urls', 'forum')),
    path('account/', include('account.urls', 'account')),

    #path('tinymce/', include('tinymce.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    # https://www.뭐뭐닷컴.com/payment/paypal 이걸 paypal의 ipn 설정에 입력하면 된다.
]

urlpatterns += staticfiles_urlpatterns()
from django.views.generic import TemplateView

# 이 아래부분 미디어 파일 디벨롭모드에서 쓰기 위해 필요
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        # path('admin/', admin.site.urls),
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
        re_path(r'^a/admin/', admin.site.urls),
    ]

wuhanproject/baseapp/forms.py
from django import forms
from baseapp.models import *
from ckeditor.widgets import CKEditorWidget

# ---------------------------------------------------------------------------------


class PostForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())
    nickname = forms.CharField()

    class Meta:
        model = Post

wuhanproject/baseapp/views.py
import feedparser
from bs4 import BeautifulSoup
from django.http import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.db.models import Q
from django.db import transaction, IntegrityError
import uuid

from django.utils.timezone import now, timedelta

# Create your views here.
from baseapp.models import *

from django.urls import reverse
from django.shortcuts import render

from django.views.decorators.http import require_GET
from django.views.decorators.csrf import csrf_exempt
import requests
# from isodata import parse_duration
from django.conf import settings

import pandas as pd
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import ast
import json
from pyvirtualdisplay import Display
import os

from django.utils.timezone import localdate
from django.utils.dateparse import parse_date
from datetime import datetime, timedelta
from ipware import get_client_ip
from geoip import geolite2

from datetime import datetime
import dateutil.parser

from forum.models import Post


def home(request):
    if request.method == "GET":
        # client_ip, is_routable = get_client_ip(request)
        client_ip = '81.169.181.179'
        country_code = None
        if client_ip is None:
            pass
        # Unable to get the client's IP address
        else:
            # print(get_client_ip(request))
            match = geolite2.lookup(client_ip)
            if match is not None:
                get_code = match.country
                try:
                    country_code = CountryCode.objects.get(code=get_code)
                except Exception as e:
                    print(e)
                    pass

                # print(match.country)# 'US'
                # print(match.continent)# 'NA'
                # print(match.timezone)# 'America/Los_Angeles'
                # print(match.subdivisions)
                # print(frozenset(['CA']))
            # We got the client's IP address
            # if is_routable:
            #     pass
            # # The client's IP address is publicly routable on the Internet
            # else:
            #     pass
        # The client's IP address is private

        date_flag = DateFlag.objects.last()
        country_item = None
        world_item = None
        all_country_item = CountryItem.objects.filter(date_flag=date_flag).order_by('-confirmed', '-death',
                                                                                    'country_code__english')
        all_country_item_chart = CountryItem.objects.filter(date_flag=date_flag).order_by('-confirmed', '-death',
                                                                                          'country_code__english')

        cnn_item = BBCItem.objects.all().order_by('-created')[:5]
        youtube_item = YoutubeItem.objects.all().order_by('-created')[:5]

        if country_code is not None:
            try:
                country_item = CountryItem.objects.get(country_code=country_code, date_flag=date_flag)
            except Exception as e:
                print(e)

        try:
            world_item = WorldItem.objects.get(date_flag=date_flag)
        except Exception as e:
            print(e)

        posts = Post.objects.filter(featured=True).order_by('-date_published').all()[:1]
        all_usa_item = USAStateItem.objects.filter(date_flag=date_flag).order_by('-confirmed', '-death',
                                                                                 'usa_state_code__english')

        if country_code is not None and country_code.code == "US":
            all_usa_item = USAStateItem.objects.filter(date_flag=date_flag).order_by('-confirmed', '-death',
                                                                                     'usa_state_code__english')

            return render(request, 'baseapp/home_usa.html', {'country_item': country_item,
                                                             'all_usa_item': all_usa_item,
                                                             'all_country_item': all_country_item,
                                                             'all_country_item_chart': all_country_item_chart,
                                                             'world_item': world_item,
                                                             'cnn_item': cnn_item,
                                                             'posts': posts})

        elif country_code is not None and country_code == "DE":
            all_germany_item = GermanyStateItem.objects.filter(date_flag=date_flag).order_by('-confirmed', '-death',
                                                                                 'germany_state_code__german')

            return render(request, 'baseapp/home_germany.html', {'country_item': country_item,
                                                             'all_germany_item': all_germany_item,
                                                             'all_country_item': all_country_item,
                                                             'all_country_item_chart': all_country_item_chart,
                                                             'world_item': world_item,
                                                             'cnn_item': cnn_item,
                                                             'posts': posts})



        # us 일 경우 home 아이콘 배치를 어떻게할까
        # dateflag 고려해서 데이터 받기.
        return render(request, 'baseapp/home.html', {'country_item': country_item,
                                                     'all_country_item': all_country_item,
                                                     'all_country_item_chart': all_country_item_chart,
                                                     'world_item': world_item,
                                                     'cnn_item': cnn_item,
                                                     'youtube_item': youtube_item,
                                                     'posts': posts})
    else:
        return render(request, 'baseapp/home.html')


def news(request):
    if request.method == "GET":

        cnn_item = BBCItem.objects.all().order_by('-created')[:50]

        return render(request, 'baseapp/news.html', {'cnn_item': cnn_item, })
    else:
        return render(request, 'baseapp/news.html')


def chart(request):
    if request.method == "GET":
        client_ip, is_routable = get_client_ip(request)
        country_code = None
        if client_ip is None:
            pass
        # Unable to get the client's IP address
        else:
            # print(get_client_ip(request))
            match = geolite2.lookup(client_ip)
            if match is not None:
                get_code = match.country
                try:
                    country_code = CountryCode.objects.get(code=get_code)
                except Exception as e:
                    print(e)
                    pass

        date_flag = DateFlag.objects.last()
        country_item = None
        world_item = None
        all_country_item = CountryItem.objects.filter(date_flag=date_flag).order_by('-confirmed', '-death',
                                                                                    'country_code__english').all()

        cnn_item = BBCItem.objects.all().order_by('-created')[:5]

        if country_code is not None:
            try:
                country_item = CountryItem.objects.get(country_code=country_code, date_flag=date_flag)
            except Exception as e:
                print(e)

        try:
            world_item = WorldItem.objects.get(date_flag=date_flag)
        except Exception as e:
            print(e)

        posts = Post.objects.filter().order_by('-date_published').all()[:1]

        return render(request, 'baseapp/chart.html', {'country_item': country_item,
                                                      'all_country_item': all_country_item,
                                                      'world_item': world_item,
                                                      'cnn_item': cnn_item,
                                                      'posts': posts})
    else:
        return render(request, 'baseapp/chart.html')


YOUTUBE_DATA_API_KEY = 'AIzaSyDAOuwrMiVMDaRxcKBGATckFTjrYlgHSGA'  # youtube api key. 민구야 발급 받는 게 좋을 듯?


@csrf_exempt
def update_bbc(request):
    if request.method == "POST":

        payload = json.loads(
            request.body.decode('utf-8'))

        token = payload["token"]
        if not token == settings.OXIBUG_TOKEN:
            return JsonResponse({"data": "failed"}, safe=False)

        url = "http://feeds.bbci.co.uk/news/rss.xml"  # Getting URL
        feed = feedparser.parse(url)  # Parsing XML data

        ids = BBCItem.objects.order_by("-pk").values_list("pk", flat=True)[:100]
        BBCItem.objects.exclude(pk__in=list(ids)).delete()

        try:
            with transaction.atomic():

                for item in feed["entries"]:
                    if 'Corona' in str(item["title"]):

                        a = str(item["description"])[:str(item["description"]).find("<img src=")]
                        cnn_item_created, created = BBCItem.objects.get_or_create(url=item['link'])
                        if created:
                            cnn_item_created.title = item["title"]
                            cnn_item_created.published_date = item["published"]
                            cnn_item_created.content = a
                            cnn_item_created.url = item['link']

                            django_date = datetime. \
                                strptime(item["published"], '%a, %d %b %Y %H:%M:%S %Z'). \
                                strftime('%Y-%m-%dT%H:%M:%S.000Z')
                            cnn_item_created.published_date_raw = dateutil.parser.parse(django_date)
                            cnn_item_created.save()

        except Exception as e:

wuhanproject/baseapp/templates/baseapp/_modal_need_login.html
<div class="modal fade" id="modal_need_login">
    <div class="modal-dialog modal-dialog_menu">
      <div class="modal-content modal-content_menu">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div align="center">need to login</div>
            <a href="/"><div align="center" class="modal_need_login clickable">login / sign up</div></a>
        </div>
      </div>
    </div>
</div>

wuhanproject/baseapp/templates/baseapp/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if all_country_item %}
        {% for item in all_country_item %}
            <div class="d-none country">
                <div class="name">{{ item.country_code.english }}</div>
                <div class="code">{{ item.country_code.code }}</div>
                <div class="case">{{ item.confirmed }}</div>
                <div class="death">{{ item.death }}</div>
                <div class="recovered">{{ item.recovered }}</div>
                <div class="death-rate">{{ item.death_rate }}</div>

            </div>
        {% endfor %}
    {% endif %}


    <div class="collapse bg-dark" id="navbarHeader" style="">
        <div class="container">
            <div class="row">
                <div class="col-md-7 py-4">
                    <h4>About</h4>
                    <p class="text-info">Tracking real time information of coronavirus worldwide in English, gathering
                        data
                        from diverse organizations globally</p>
                </div>
                <div class="col-md-3 offset-md-1 py-4">
                    <h4>Contact</h4>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#" class="text-secondary">Follow on Twitter</a>
                        </li>
                        <li>
                            <a href="#" class="text-secondary">Like on Facebook</a>
                        </li>
                        <li>
                            <a href="#" class="text-secondary">Email me</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="py-3" style="">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center d-block d-md-none">coronagram</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="py-4" style="">
        <div class="container">
            <div class="row">
                <div class="col-md-12 chartdiv1" style="width: 100%; height: 320px;"></div>
            </div>
        </div>
    </div>
    <div class="" style="">
        <div class="container">
            <div class="row">
                <div class="col-md-12 pt-2">
                    <h4 class="text-center">World ({{ world_item.country_count }} Countries)</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="py-2" style="">
        <div class="container">
            <div class="row">
                <div class="col-3 border-top border-secondary" style="">
                    <p class="text-center" style="">Confirmed</p>
                    <p class="text-center">{{ world_item.confirmed }}</p>
                </div>
                <div class="col-3 border-top border-secondary" style="">
                    <p class="text-center text-danger" style="">Deaths</p>
                    <p class="text-center">{{ world_item.death }}</p>
                </div>
                <div class="col-3 border-top border-secondary" style="">
                    <p class="text-center" style="">Death%</p>
                    <p class="text-center">{{ world_item.death_rate }}%</p>
                </div>
                <div class="col-3 border-top border-secondary" style="">
                    <p class="text-center" style="">Recovered</p>
                    <p class="text-center">{{ world_item.recovered }}</p>
                </div>
            </div>
        </div>
    </div>
    {% if country_item %}
        <div class="" style="">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 pt-4">
                        <h4 class="text-center">{{ country_item.country_code.english }}</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="py-2" style="">
            <div class="container">
                <div class="row">
                    <div class="col-3 border-top border-secondary" style="">
                        <p class="text-center" style="">Confirmed</p>
                        <p class="text-center">{{ country_item.confirmed }}</p>
                    </div>
                    <div class="col-3 border-top border-secondary" style="">
                        <p class="text-center text-danger" style="">Deaths</p>
                        <p class="text-center">{{ country_item.death }}</p>
                    </div>
                    <div class="col-3 border-top border-secondary" style="">
                        <p class="text-center" style="">Death%</p>
                        <p class="text-center">{{ country_item.death_rate }}%</p>
                    </div>
                    <div class="col-3 border-top border-secondary" style="">
                        <p class="text-center" style="">Recovered</p>
                        <p class="text-center">{{ country_item.recovered }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <div class="p-1" style="">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h4 class="text-center">Forum</h4>
                </div>
            </div>

            {% if posts %}
                {% for post in posts %}
                    <a href="{% url 'forum:detail' id=post.id title=post.title %}">
                        <div class="row">
                            <div class="col-md-8 mx-auto py-1 m-1 border rounded border-secondary" style="">
                                <p class=""><b>{{ post.title }}</b><span class="font-weight-normal"> by <span
                                        class="font-italic">{{ post.author.username }}</span></span>
                                </p>
                                <p class="lead py-0">{{ post.body|safe|truncatechars:30 }}</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}
        </div>
        <div class="container">
            <a href="{% url 'forum:post_list' %}">
                <div class="row">
                    <button class="col-md-8 mx-auto text-center btn btn-primary p-2">More Posts</button>
                </div>
            </a>
        </div>
    </div>

    <div class="pt-0 mt-4">
        <div class="container">
            <div class="row">
                <div class="col-12 mx-auto">
                    <p class="">Data updated: {{ world_item.date_flag.created|timesince }} ago</p>
                </div>
            </div>
        </div>
    </div>
    <div class="pt-0 mt-0" style="">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="">
                    <div class="table-responsive">
                        <table class="table table-striped table-borderless">
                            <thead>
                            <tr>
                                <td scope="col" class="w-25"></td>
                                <td scope="col" class="w-25">Confirmed</td>
                                <td scope="col" class="w-25">Deaths</td>
                                <td scope="col" class="w-25">Recov</td>
                            </tr>
                            </thead>
                            <tbody>

                            {% for all_item in all_country_item_chart %}
                                <tr>
                                    <td>{{ forloop.counter }} {{ all_item.country_code.english }}</td>
                                    <td style="">{{ all_item.confirmed }}</td>
                                    <td style="">{{ all_item.death }}</td>
                                    <td style="">{{ all_item.recovered }}</td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--<div class="container">
        <a href="{% url 'baseapp:chart' %}">
            <div class="row p-1">
                <button class="col-md-8 mx-auto text-center btn btn-primary p-2">More Countries</button>
            </div>
        </a>
    </div>-->

    {% if cnn_item %}

        <div class="pt-3" style="">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Corona News</h4>
                    </div>
                </div>
            </div>
        </div>
        {% for cnn in cnn_item %}

            <div class="py-2">
                <div class="container">

                    <a href="{{ cnn.url }}"
                       target="_blank" rel="noopener noreferrer">
                        <div class="row">
                            <div class="col-md-12">
                                <h6 class="">{{ cnn.title }}</h6>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p class="lead">{{ cnn.content }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p>{{ cnn.published_date_raw|timesince }} ago</p>
                            </div>
                        </div>

                    </a>
                </div>
            </div>

        {% endfor %}
        <div class="container">
            <a href="{% url 'baseapp:news' %}">
                <div class="row">
                    <button class="col-md-8 mx-auto text-center btn btn-primary p-2">More News</button>
                </div>
            </a>
        </div>
    {% endif %}


    <div class="py-3">
        <div class="container">
            <div class="row">
                <div class="col-6 text-center" style=""><a class="btn text-white col-10"
                                                           href="http://www.facebook.com/sharer.php?u=https://www.coronagram.com{{ request.get_full_path }}"
                                                           style="background:#3b5998"
                                                           target="_blank"><i
                        class="fa fa-facebook-square fa-fw fa-1x py-1"></i> Share</a></div>
                <div class="col-6 col-md-6 text-center"><a class="btn text-white col-10"
                                                           href="https://twitter.com/share?url=https://www.coronagram.com{{ request.get_full_path }}"
                                                           style="background:#55acee"
                                                           target="_blank"><i
                        class="fa fa-twitter fa-fw fa-1x py-1"></i>
                    Tweet</a></div>
            </div>
        </div>
    </div>
    <div class="py-3">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-uppercase">
                    <h6 class="text-center bg-info">Source</h6>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <a href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports"
                       target="_blank" rel="noopener noreferrer"><h6 class="text-center">WHO</h6></a>
                    <a href="https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases" target="_blank"
                       rel="noopener noreferrer"><h6 class="text-center">ECDC</h6></a>
                    <a href="https://www.cdc.gov/coronavirus/2019-ncov/index.html" target="_blank"
                       rel="noopener noreferrer"><h6 class="text-center">CDC</h6></a>
                    <a href="http://www.nhc.gov.cn/yjb/s3578/new_list.shtml" target="_blank" rel="noopener noreferrer">
                        <h6
                                class="text-center">NHC</h6></a>
                    <a href="https://ncov.dxy.cn/ncovh5/view/pneumonia?scene=2" target="_blank"
                       rel="noopener noreferrer">
                        <h6 class="text-center">DXY</h6></a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

wuhanproject/baseapp/templates/baseapp/news.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% if cnn_item %}

        <div class="pt-3" style="">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Corona News 50</h4>
                    </div>
                </div>
            </div>
        </div>
        {% for cnn in cnn_item %}

            <div class="py-2">
                <div class="container">

                    <a href="{{ cnn.url }}"
                       target="_blank" rel="noopener noreferrer">
                        <div class="row">
                            <div class="col-md-12">
                                <h6 class="">{{ cnn.title }}</h6>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p class="lead">{{ cnn.content }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p>{{ cnn.published_date_raw|timesince }} ago</p>
                            </div>
                        </div>

                    </a>
                </div>
            </div>

        {% endfor %}
        <div class="container">
            <a href="{% url 'baseapp:home' %}">
                <div class="row">
                    <button class="col-md-8 mx-auto text-center btn btn-primary p-2">Back to Home</button>
                </div>
            </a>
        </div>
    {% endif %}


    <div class="py-3">
        <div class="container">
            <div class="row">
                <div class="col-6 text-center" style=""><a class="btn text-white col-10"
                                                           href="http://www.facebook.com/sharer.php?u=https://www.coronagram.com{{ request.get_full_path }}"
                                                           style="background:#3b5998"
                                                           target="_blank"><i
                        class="fa fa-facebook-square fa-fw fa-1x py-1"></i> Share</a></div>
                <div class="col-6 col-md-6 text-center"><a class="btn text-white col-10"
                                                           href="https://twitter.com/share?url=https://www.coronagram.com{{ request.get_full_path }}"
                                                           style="background:#55acee"
                                                           target="_blank"><i
                        class="fa fa-twitter fa-fw fa-1x py-1"></i>
                    Tweet</a></div>
            </div>
        </div>
    </div>
{% endblock content %}